// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react';
import { useOutlet, history } from 'dumi';

import nprogress from 'E:/Github/BingTang-Doc/node_modules/.pnpm/nprogress@0.2.0/node_modules/nprogress';
import './nprogress.css';

import { SiteContext } from 'E:/Github/BingTang-Doc/node_modules/.pnpm/dumi@2.1.24_@babel+core@7.21.8_@types+node@20.1.4_@types+react@18.2.6_eslint@8.40.0_postcss@8_q46csgyzljcrkq75ppc3duui3u/node_modules/dumi/dist/client/theme-api/context.js';
import { demos, components } from '../meta';
import { locales } from '../locales/config';

const entryExports = {
  
  
};

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(true);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // mark loading when route change, page component will set false when loaded
        setLoading(true);

        // start nprogress
        nprogress.start();

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  return (
    <SiteContext.Provider value={{
      pkg: {"name":"@Bing-Plugins/Bing-Doc","description":"a npm develop template","version":"1.7.0","license":"MIT","repository":{"type":"git","url":"https://github.com/arvinxx/npm-template.git"},"author":"arvinxx(arvinx@foxmail.com)"},
      historyType: "browser",
      entryExports,
      demos,
      components,
      locales,
      loading,
      setLoading,
      themeConfig: {"footer":false,"prefersColor":{"default":"light","switch":true},"nprogress":true,"name":"BingTang Docs","github":"https://github.com/Bing-Plugins/BingTang-Doc","showLineNum":true,"rtl":true},
    }}>
      {outlet}
    </SiteContext.Provider>
  );
}
